name: C/C++ CI

on:
  push:
    branches: [ dev-cicd ]
  pull_request:
    branches: [ dev-cicd ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
    - name: install packages
      run: sudo apt-get install -y libgirepository1.0-dev guile-3.0-dev gnulib texlive
    - name: look for guile
      run: ls -l /usr/bin/gu*
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: GUILD=/usr/bin/guild ./configure --enable-hardening
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: GUILD=/usr/bin/guild make distcheck
